### ISSUE TITLE
Difference with existing workflow?

### ISSUE THREAD

**Issue by articuluxe** [emacs-pe/crontab-mode#2]
Hello, I was just wondering if you have any comments regarding differences between this new package and the existing available at the [wiki](https://www.emacswiki.org/emacs/CrontabMode).

Thank you.

**Comment by marsam** [comment]
Hi:
Sorry for the late response. To be honest, I didn't know about the crontab-mode from emacswiki when I wrote this package. 

From a cursory reading, the main difference could be that crontab-mode from emacswiki _imposes_ a workflow, from their `Commentary:`
```elisp
;; * I want to keep my crontabs under rcs to keep a history of
;;   the file.  Editing them with 'crontab -e' is rather
;;   cumbersome.  My method is to keep the crontab as a file,
;;   under rcs, and check in the changes with 'C-c C-c' after
;;   editing.
```
So, for instance, it adds commands to _install_ crontab in remote hosts.

This mode instead offers just syntax highlighting, and doesn't make any assumption about your workflow.

I hope that answers your question.
